name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
        type: string

jobs:
  create-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      
      - name: Build release binary
        run: cargo build --release --target x86_64-apple-darwin
        
      - name: Create release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: |
            target/x86_64-apple-darwin/release/cli-doc
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
