name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
        type: string

jobs:
  create-release:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            extension: .exe
            runner: windows-latest
          - target: x86_64-apple-darwin
            extension: .zip
            runner: macos-latest

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Set up Zip File
        if: ${{ matrix.runner == 'macos-latest'}}
        run: |
          zip -r target/${{ matrix.target }}/release/cli-doc${{ matrix.extension }} target/${{ matrix.target }}/release/cli-doc${{ matrix.extension }}


      - name: Create release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: |
            target/${{ matrix.target }}/release/cli-doc${{ matrix.extension }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
